# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.76

## Mod Properties
mod_id=wgiyv
mod_build=wgiyv-neo
mod_name=WGIYV
mod_license=https://github.com/MasterGeneral156/WGIYV/blob/26.1.2/LICENSE
mod_version=26.1.2-1.4.0
mod_group_id=com.themastergeneral.wgiyv
mod_authors=TheMasterGeneral
mod_description=Show off to the world you vape by toking on this vape, bro.
ctd_core_ver=26.1.2-2.9.6
